//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAgentSystem2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public System.Guid AchievementID { get; set; }
        public System.Guid AgentID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> AchievementLevelID { get; set; }
    
        public virtual AchievementLevel AchievementLevel { get; set; }
        public virtual Agent Agent { get; set; }
    }
}
