//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAgentSystem2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgentSystem : DbContext
    {
        public AgentSystem()
            : base("name=AgentSystem")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<AgentLocation> AgentLocation { get; set; }
        public virtual DbSet<AgentStatus> AgentStatus { get; set; }
        public virtual DbSet<Coordinate> Coordinate { get; set; }
        public virtual DbSet<Goal> Goal { get; set; }
        public virtual DbSet<Mission> Mission { get; set; }
        public virtual DbSet<MissionStatus> MissionStatus { get; set; }
        public virtual DbSet<AgentLocationCoordinate> AgentLocationCoordinate { get; set; }
        public virtual DbSet<Achievement> Achievement { get; set; }
        public virtual DbSet<AchievementLevel> AchievementLevel { get; set; }
        public virtual DbSet<Message> Message { get; set; }
    }
}
