//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAgentSystem2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentLocationCoordinate
    {
        public System.Guid AgentLocationID { get; set; }
        public System.Guid CoordinateID { get; set; }
        public System.Guid AgentLocationCoordinateID { get; set; }
    
        public virtual AgentLocation AgentLocation { get; set; }
        public virtual Coordinate Coordinate { get; set; }
    }
}
