//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAgentSystem2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coordinate()
        {
            this.AgentLocationCoordinate = new HashSet<AgentLocationCoordinate>();
        }
    
        public System.Guid CoordinateID { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentLocationCoordinate> AgentLocationCoordinate { get; set; }
    }
}
