//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAgentSystem2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goal()
        {
            this.Message = new HashSet<Message>();
        }
    
        public System.Guid GoalID { get; set; }
        public System.Guid MissionID { get; set; }
        public System.Guid AgentID { get; set; }
        public System.Guid CoordinateID { get; set; }
        public string AgentFeedback { get; set; }
        public bool AgentCompletedFlag { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Coordinate Coordinate { get; set; }
        public virtual Mission Mission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message { get; set; }
    }
}
